name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Or 'main' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Configure Git User
        run: |
          git config --global user.name "j-effrey"
          git config --global user.email "actions@github.com" # Or your actual email

      - name: Deploy to GitHub Pages
        # The key change is adding the --repo argument to the gh-pages command
        run: npm run deploy -- --repo https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Still good to keep this, gh-pages might use it for other API calls
